// Build-time generator: for every (method, scramble, phase) it solves the
// canonical block goal from the post-scramble state (cumulatively, so each
// phase continues from the previous one) and writes verified ideal solutions
// to src/journeys.ideals.ts. Run with: npm run gen
//
// Node 23.6+/24 runs this .ts file directly via type-stripping.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { applyScramble, applyMoveList, solvedCube, goalSolved } from '../src/cube.ts';
import { solveBlock } from '../src/solver.ts';
import { METHODS, SCRAMBLES, ideObjKey, type Method } from '../src/journeys.def.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));

const ideals: Record<string, string> = {};

for (const methodName of Object.keys(METHODS) as Method[]) {
  const def = METHODS[methodName];
  for (const scr of SCRAMBLES) {
    let cube = applyScramble(solvedCube(), scr.scramble);
    for (const phase of def.phases) {
      const sol = solveBlock(cube, phase.goal, { maxDepth: 16 });
      if (sol === null) {
        console.warn(`! No solution within depth cap: ${methodName} ${scr.id} ${phase.id}`);
        ideals[ideObjKey(methodName, scr.id, phase.id)] = '';
        continue;
      }
      const ideal = sol.join(' ');
      ideals[ideObjKey(methodName, scr.id, phase.id)] = ideal;
      // advance cube by the ideal so the next phase continues from here
      cube = applyMoveList(cube, sol);
      if (!goalSolved(cube, phase.goal)) {
        console.error(`!! Generated ideal does not solve goal: ${methodName} ${scr.id} ${phase.id}`);
      }
      console.log(`${methodName} ${scr.id} ${phase.id}: ${sol.length} moves  [${ideal}]`);
    }
  }
}

const header = `// AUTO-GENERATED by scripts/gen-journeys.ts — do not edit by hand.
// Verified ideal block-building solutions, keyed by "Method::scrambleId::phaseId".

export const IDEALS: Record<string, string> = ${JSON.stringify(ideals, null, 2)};
`;

const outPath = join(__dirname, '..', 'src', 'journeys.ideals.ts');
writeFileSync(outPath, header, 'utf8');
console.log(`\nWrote ${Object.keys(ideals).length} ideals to ${outPath}`);
