// AUTO-GENERATED by scripts/gen-journeys.ts — do not edit by hand.
// Verified ideal block-building solutions, keyed by "Method::scrambleId::phaseId".

export const IDEALS: Record<string, string> = {
  "Petrus::s1::p222": "U R' U2 L2 U2 L D",
  "Petrus::s1::p223": "U2 R B2 U' B2 U' B",
  "Petrus::s2::p222": "U B L F' U B2 D2",
  "Petrus::s2::p223": "U2 B R' B2 U B2",
  "Petrus::s3::p222": "U L2 U R' D' L2",
  "Petrus::s3::p223": "R2 B U2 R2 U2 B",
  "APB::s1::a222": "U R' U2 L2 U2 L D",
  "APB::s1::a223": "U2 R B2 U' B2 U' B",
  "APB::s2::a222": "U B L F' U B2 D2",
  "APB::s2::a223": "U2 B R' B2 U B2",
  "APB::s3::a222": "U L2 U R' D' L2",
  "APB::s3::a223": "R2 B U2 R2 U2 B",
  "Roux::s1::r1": "U L D2 R2 B D'",
  "Roux::s1::r2": "D R D' R2 B' L D'",
  "Roux::s2::r1": "D2 B' U2 B2 U' F'",
  "Roux::s2::r2": "U R F2 R F D F2",
  "Roux::s3::r1": "R B2 R2 F L' F'",
  "Roux::s3::r2": "U' F U B U2 L' D2 B'",
  "LEOR::s1::l1": "U L D2 R2 B D'",
  "LEOR::s1::l2": "D R D' R2 B' L D'",
  "LEOR::s2::l1": "D2 B' U2 B2 U' F'",
  "LEOR::s2::l2": "U R F2 R F D F2",
  "LEOR::s3::l1": "R B2 R2 F L' F'",
  "LEOR::s3::l2": "U' F U B U2 L' D2 B'"
};
